### ISSUE TITLE
hardcoded path

### ISSUE THREAD

**Issue by janisozaur** [xgdapg/atom-rustfmt#2]
This seems to have path to `rustfmt` hardcoded and no way to change it.

`rustfmt` should be detected or user should be given an option to provide own path.

**Comment by xgdapg** [comment]
@janisozaur
Actually there is an option. 
You can find it at Settings / Packages / rustfmt / Settings / “Path to the rustfmt executable" and change it.

**Comment by janisozaur** [comment]
yes, indeed. Somehow I didn't notice it yesterday, I believe there was no `settings` button at all available for this plugin.

I have installed few rust plugins at once, all of which used wrong path by default, perhaps this somehow affected atom.

As there is a user-facing way to change the path, I will close this issue then.
