### ISSUE TITLE
Don't provide a full path for rustfmt executable

### ISSUE THREAD

**Issue by bendem** [xgdapg/atom-rustfmt#3]
Default value for `rustfmt`'s executable is `/usr/local/bin/rustfmt` which prevents retrieving it from the `PATH` making the error message very unclear:

> Make sure `/usr/local/bin/rustfmt` is installed and on your `PATH`

I propose to simply default to `rustfmt`, allowing most users to use the package without configuration since `rustfmt` is generally in the path but not forcibly in `/usr/local/bin`.

**Comment by xgdapg** [comment]
Fixed. Thanks.

**Comment by bendem** [comment]
thanks
